### ISSUE TITLE
In the reports, what is the detail section for?

### ISSUE THREAD

**Issue by prafulbagai** [piglei/uwsgi-sloth#13] opened 2019-07-11 16:51 UTC
My application serves 90% of the traffic on a specific URL.  Hence, my log file is filled with below logline.

`
[pid: 25827|app: 0|req: 18/18] 162.158.158.173 () {62 vars in 1255 bytes} [Thu Jul 11 22:08:38 2019] POST /apis/shops/get_aff_url/ => generated 274 bytes in 23 msecs (HTTP/1.1 404) 5 headers in 152 bytes (1 switches on core 0)`

However, in the reports, I don't see this URL under the detail section.

Below is the screenshot of `Today` period.

<img width="1057" alt="Screenshot 2019-07-11 at 10 15 41 PM" src="https://user-images.githubusercontent.com/4829481/61069396-d7a46380-a429-11e9-81eb-2918e6a1c722.png">

**Issues**

1) I don't see `/apis/shops/get_aff_url/ ` in the reports at all, even when it was hit 90% of the time.

2) Total requests are 491, which is incorrect. I'd over 2000 hits on the above URL, and around 100 requests on the other URLs.

Kindly help in explaining the reports.

**Comment by piglei** [comment] 2019-07-12 09:31
Hi, The "details" field was supposed to contain all requests which were marked as "slow requests", by default, the threshould is 200 msecs, which means all requests which takes more than 200 msecs will be recorded and displayed in the "details" field.

Your issues:

1. Maybe it's just because the endpoint "/apis/shops/get_aff_url/"  's respond time is too short for it to be recorded.
2. This is abnormal, could you upload your log file so I can try reproduce this issue?

**Comment by prafulbagai** [comment] 2019-07-13 13:22
Here is the logfile:- [uwsgi.log](https://github.com/piglei/uwsgi-sloth/files/3388794/uwsgi.log)

Counting lines by pattern `Fri Jul 12` (ie yesterday's date) in the log file:-

`grep -w "Fri Jul 12" -c uwsgi.log`  # returns `2036`

However in my [Analytics dashboard](http://zoffer.in/analytics), yesterday's count show `413` requests. 

Let me know if you're able to reproduce the issue.

**Comment by piglei** [comment] 2019-07-21 07:40
I checked your log file, found out that a majority of requests's status code is 404. Because Uwsgi-sloth was configured to count 200 requests only, the html report contains a smaller requests count.

**Closed as completed by piglei** 2019-07-21 07:40 UTC

**Comment by prafulbagai** [comment] 2019-07-21 09:53
How and where can I configure to consider all HTTP requests?

**Comment by prafulbagai** [comment] 2019-07-21 09:55
Or better there can be a flag that can enable or disable the different types of requests?

**Comment by prafulbagai** [comment] 2019-07-21 10:14
Okay. I forked your amazing repo and set the setting to consider all HTTP status code. Thanks for your work.

However, is there any specific reason to consider only 200 request?

**Comment by piglei** [comment] 2019-07-21 23:01
While I cann't recall any specific reason at this moment, maybe requests other than 200 doesn't make any sense when this tool was initially written for my personal website.

I think the status restriction should be removed or become configurable, I will update it later.
